/* EGPD — production module list. Builds MODULES from js/modules/egpd/module-egpd-N.js (loaded first by index.html).
   contentHtml is the module reading page (READING_* consts defined in each module file); the scenario engine and
   quizzes hang off the same entry. */

/* Supervisor track: the reading served to supervisors is the officer reading
   PLUS a command-lens overlay injected just before the scenario button. One
   source of truth for the base law (no duplicated legal text to drift); the
   resolver in app.js (activeContentHtml / activeQuestions) picks the supervisor
   variants when currentUser.track === 'supervisor'. */
function withSupervisorOverlay(base, overlay) {
    return base.replace(
        /(<button class="btn-launch"[^>]*>Proceed to Scenario Exercise →<\/button>)/,
        `</div>\n${overlay}\n  <div class="content-block">\n    $1`
    );
}

const MODULES = [
    { id: 'egpd-search-seizure', category: 'Constitutional Law', title: 'Search & Seizure — Fourth Amendment', description: 'EGPD', duration: '20–25 min', weekNumber: 1, contentHtml: READING_SEARCH_SEIZURE, debriefHtml: DEBRIEF_SEARCH_SEIZURE, supervisorContentHtml: withSupervisorOverlay(READING_SEARCH_SEIZURE, SUPERVISOR_SEARCH_SEIZURE), scenario: SCENARIO_SEARCH_SEIZURE, supervisorScenario: SCENARIO_SEARCH_SEIZURE_SUP, questions: getSearchSeizureQuestions(), supervisorQuestions: getSearchSeizureSupervisorQuestions() },
    { id: 'egpd-use-of-force', category: 'Use of Force', title: 'Use of Force Continuum', description: 'EGPD', duration: '15–20 min', weekNumber: 2, contentHtml: READING_USE_OF_FORCE, debriefHtml: DEBRIEF_USE_OF_FORCE, supervisorContentHtml: withSupervisorOverlay(READING_USE_OF_FORCE, SUPERVISOR_USE_OF_FORCE), scenario: SCENARIO_USE_OF_FORCE, supervisorScenario: SCENARIO_USE_OF_FORCE_SUP, questions: getUseOfForceQuestions(), supervisorQuestions: getUseOfForceSupervisorQuestions() },
    { id: 'egpd-report-writing', category: 'Documentation', title: 'Professional Report Writing', description: 'EGPD', duration: '10–15 min', weekNumber: 3, contentHtml: READING_REPORT_WRITING, debriefHtml: DEBRIEF_REPORT_WRITING, supervisorContentHtml: withSupervisorOverlay(READING_REPORT_WRITING, SUPERVISOR_REPORT_WRITING), scenario: SCENARIO_REPORT_WRITING, supervisorScenario: SCENARIO_REPORT_WRITING_SUP, questions: getReportWritingQuestions(), supervisorQuestions: getReportWritingSupervisorQuestions() },
    { id: 'egpd-crisis-intervention', category: 'Crisis Response', title: 'Crisis Intervention & De-Escalation', description: 'EGPD', duration: '20–25 min', weekNumber: 4, contentHtml: READING_CRISIS, debriefHtml: DEBRIEF_CRISIS, supervisorContentHtml: withSupervisorOverlay(READING_CRISIS, SUPERVISOR_CRISIS), scenario: SCENARIO_CRISIS, supervisorScenario: SCENARIO_CRISIS_SUP, questions: getCrisisQuestions(), supervisorQuestions: getCrisisSupervisorQuestions() },
    { id: 'egpd-domestic-violence', category: 'Domestic Violence', title: 'Domestic Violence Response', description: 'EGPD', duration: '20–25 min', weekNumber: 5, contentHtml: READING_DOMESTIC_VIOLENCE, debriefHtml: DEBRIEF_DOMESTIC_VIOLENCE, supervisorContentHtml: withSupervisorOverlay(READING_DOMESTIC_VIOLENCE, SUPERVISOR_DOMESTIC_VIOLENCE), scenario: SCENARIO_DOMESTIC_VIOLENCE, supervisorScenario: SCENARIO_DOMESTIC_VIOLENCE_SUP, questions: getDomesticViolenceQuestions(), supervisorQuestions: getDomesticViolenceSupervisorQuestions() },
    { id: 'egpd-vehicle-pursuits', category: 'Traffic & Pursuits', title: 'Motor Vehicle Pursuits', description: 'EGPD', duration: '15–20 min', weekNumber: 6, contentHtml: READING_VEHICLE_PURSUITS, debriefHtml: DEBRIEF_VEHICLE_PURSUITS, supervisorContentHtml: withSupervisorOverlay(READING_VEHICLE_PURSUITS, SUPERVISOR_VEHICLE_PURSUITS), scenario: SCENARIO_VEHICLE_PURSUITS, supervisorScenario: SCENARIO_VEHICLE_PURSUITS_SUP, questions: getVehiclePursuitQuestions(), supervisorQuestions: getVehiclePursuitSupervisorQuestions() },
    { id: 'egpd-leadership', category: 'Professional Development', title: 'Leadership & Supervision', description: 'EGPD', duration: '20–25 min', weekNumber: 7, contentHtml: READING_LEADERSHIP, debriefHtml: DEBRIEF_LEADERSHIP, supervisorContentHtml: withSupervisorOverlay(READING_LEADERSHIP, SUPERVISOR_LEADERSHIP), scenario: SCENARIO_LEADERSHIP, supervisorScenario: SCENARIO_LEADERSHIP_SUP, questions: getLeadershipQuestions(), supervisorQuestions: getLeadershipSupervisorQuestions() },
    { id: 'egpd-traffic-stops', category: 'Traffic & Contacts', title: 'Traffic Stops & Vehicle Contacts', description: 'EGPD', duration: '20–25 min', weekNumber: 8, contentHtml: READING_TRAFFIC_STOPS, debriefHtml: DEBRIEF_TRAFFIC_STOPS, supervisorContentHtml: withSupervisorOverlay(READING_TRAFFIC_STOPS, SUPERVISOR_TRAFFIC_STOPS), scenario: SCENARIO_TRAFFIC_STOPS, supervisorScenario: SCENARIO_TRAFFIC_STOPS_SUP, questions: getTrafficStopQuestions(), supervisorQuestions: getTrafficStopSupervisorQuestions() },
    { id: 'egpd-emotional-intelligence', category: 'Professional Development', title: 'Emotional Intelligence', description: 'EGPD', duration: '15–20 min', weekNumber: 9, contentHtml: READING_EI, debriefHtml: DEBRIEF_EI, supervisorContentHtml: withSupervisorOverlay(READING_EI, SUPERVISOR_EI), scenario: SCENARIO_EI, supervisorScenario: SCENARIO_EI_SUP, questions: getEIQuestions(), supervisorQuestions: getEISupervisorQuestions() },
    { id: 'egpd-evidence-chain-of-custody', category: 'Investigations', title: 'Evidence & Chain of Custody', description: 'EGPD', duration: '15–20 min', weekNumber: 10, contentHtml: READING_EVIDENCE, debriefHtml: DEBRIEF_EVIDENCE, supervisorContentHtml: withSupervisorOverlay(READING_EVIDENCE, SUPERVISOR_EVIDENCE), scenario: SCENARIO_EVIDENCE, supervisorScenario: SCENARIO_EVIDENCE_SUP, questions: getEvidenceQuestions(), supervisorQuestions: getEvidenceSupervisorQuestions() },
    { id: 'egpd-officer-wellness', category: 'Wellness', title: 'Officer Wellness', description: 'EGPD', duration: '15–20 min', weekNumber: 11, contentHtml: READING_WELLNESS, debriefHtml: DEBRIEF_WELLNESS, supervisorContentHtml: withSupervisorOverlay(READING_WELLNESS, SUPERVISOR_WELLNESS), scenario: SCENARIO_WELLNESS, supervisorScenario: SCENARIO_WELLNESS_SUP, questions: getWellnessQuestions(), supervisorQuestions: getWellnessSupervisorQuestions() },
    { id: 'egpd-de-escalation', category: 'Use of Force', title: 'De-escalation', description: 'EGPD', duration: '15–20 min', weekNumber: 12, contentHtml: READING_DEESCALATION, debriefHtml: DEBRIEF_DEESCALATION, supervisorContentHtml: withSupervisorOverlay(READING_DEESCALATION, SUPERVISOR_DEESCALATION), scenario: SCENARIO_DEESCALATION, supervisorScenario: SCENARIO_DEESCALATION_SUP, questions: getDeescalationQuestions(), supervisorQuestions: getDeescalationSupervisorQuestions() },
];
